# Generated by Django 4.1.5 on 2023-01-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
