# Generated by Django 4.1.5 on 2023-01-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_alter_pet_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
