# Generated by Django 4.1.5 on 2023-01-18 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoadocao',
            options={'verbose_name_plural': 'PedidoAdoções'},
        ),
    ]
